deployment:
  container:
    cpuLimit: 1
    cpuRequest: 0.5
    digest: sha256:65c98e9a5bd03be73b9ba2ce77a6eab195379a5339e2ced63339ff0198b4ef1b
    healthPath: /
    image: ahmedgrati/videos-webapp
    memoryLimit: 500Mi
    memoryRequest: 500Mi
    name: videos-web-container
    port: 80
  name: videos-web
  namespace: frontend
  replicas: 1
serviceAccount:
  name: videos-web-sa
service:
  name: videos-web
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
ingress:
  enabled: true
  rules:
    - name: videos-web-ingress
      host: kubees.videos.app.com
      path: /
      service: videos-web
      port: 80
