apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    {{- range .Values.service.ports }}
    - protocol: {{ .protocol }}
      name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{ end }}