name: Helm Chart CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run Checkov Analysis
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          directory: webapp-helm-chart/
          quiet: true
          skip_check: CKV_K8S_23,CKV_K8S_28,CKV_K8S_22,CKV_K8S_40,CKV_K8S_37
          framework: helm 
          output_format: sarif 
          output_file_path: reports/results.sarif
          download_external_modules: true
#      - name: Upload Analysis Report
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: reports/results.sarif
#          category: checkov-analysis
